name: Deploy Get Item Lambda

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/get_item_lambda.yml'
      - 'ServerlessAPI/get_item_lambda/**'
  workflow_dispatch:
  

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: 'us-east-2'
  BUILD_ENV: 'prod'
  DEPLOY_ENV: 'prod'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ServerlessAPI/get_item_lambda/cdk/requirements.txt

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install AWS CDK
      run: npm install -g aws-cdk

    - name: Install Node.js dependencies and build GetSampleItemFunc
      run: |
        npm install
        npm run build
      working-directory: ServerlessAPI/get_item_lambda
      
    - name: Build CDK stack
      run: cdk synth -c env=${{ env.BUILD_ENV }}
      working-directory: ServerlessAPI/get_item_lambda/cdk

    - name: Deploy CDK stack
      run: cdk deploy --require-approval never -c env=${{ env.DEPLOY_ENV }}
      working-directory: ServerlessAPI/get_item_lambda/cdk
