name: Deploy ServerlessAPI Common Stack

on:
  push:
    branches:
      #- main
      - ServerlessAPI-AdditionalEndpoints
    paths:
      - '.github/workflows/serverless-api-stack.yml'
      - 'ServerlessAPI/common_stack/**'
  workflow_dispatch:
  

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: 'us-east-2'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ServerlessAPI/common_stack/requirements.txt

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install AWS CDK
      run: npm install -g aws-cdk

    - name: Install Node.js dependencies and build HealthCheckFunc
      run: |
        npm install
        npm run build
      working-directory: ServerlessAPI/common_stack/health_check_lambda

    # - name: Install Node.js dependencies and build GetSampleItemFunc
    #   run: |
    #     npm install
    #     npm run build
    #   working-directory: ServerlessAPI/get_item_lambda
    
    # - name: Install Node.js dependencies and build InsertSampleItemFunc
    #   run: |
    #     npm install
    #     npm run build
    #   working-directory: ServerlessAPI/add_item_lambda
    
    # - name: Install Node.js dependencies and build UpdateSampleItemFunc
    #   run: |
    #     npm install
    #     npm run build
    #   working-directory: ServerlessAPI/update_item_lambda

    # - name: Install Node.js dependencies and build DeleteSampleItemFunc
    #   run: |
    #     npm install
    #     npm run build
    #   working-directory: ServerlessAPI/delete_item_lambda
      
    - name: Build CDK stack
      run: cdk synth -c env=prod
      working-directory: ServerlessAPI/common_stack

    - name: Deploy CDK stack
      run: cdk deploy --require-approval never -c env=prod
      working-directory: ServerlessAPI/common_stack
